experiment_name: touche2020_FIXED_05
evaluation_profile: default
execution_profile: default
dataset:
  name: beir/webis-touche2020
  normalized_dir: data/normalized/beir/webis-touche2020
  split: test
  download_if_missing: true
split:
  type: sentence
  model: en_core_web_sm
  output_path: data/processed/webis-touche2020/sentences.jsonl
router:
  enabled: false
  name: moc
chunking:
  type: fixed
  dataset: webis-touche2020
  save_chunks: false
  n_chunks: 10
  overlap_sentences: 1
embedding:
  name: stella
  batch_size: 32
  normalize_embeddings: true
  show_progress_bar: false
retrieval:
  enabled: true
  backend: dense_faiss
  distance: cosine
  normalize: true
evaluation:
  intrinsic_model:
    backend: lexical
  extrinsic_tasks_to_run:
  - document_retrieval
  - evidence_retrieval
  - answer_generation
  extrinsic_tasks:
    answer_generation:
      reader_backend: seq2seqlm
      reader_model: google/flan-t5-base
      top_k: 5
